version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: GraphQL
    versions:
    - 3.3.2
    - 4.0.1
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.3.0
    - 4.4.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
